"""Partition the static font offline; requires fonttools==4.65.0."""

import hashlib
import json
from pathlib import Path
import sys
import fontTools
from fontTools import subset
from fontTools.ttLib import TTFont

source, latin_path, destination = map(Path, sys.argv[1:4])
assert fontTools.__version__ == "4.65.0", "Use the pinned FontTools version"
assert hashlib.sha256(source.read_bytes()).hexdigest() == "dd53a28f9fabaf20ba1e136b00c60cc726cbde0609b16ef332cee5616efe83c4", "Unexpected CJK source"
assert hashlib.sha256(latin_path.read_bytes()).hexdigest() == "b85c38ecea8a7cfb39c24e395a4007474fa5a4fc864f6ee33309eb4948d232d5", "Unexpected Latin source"
destination.mkdir(parents=True, exist_ok=True)
chunk_size = 64


def ranges(points):
    result = []
    for point in sorted(points):
        if result and point == result[-1][1] + 1:
            result[-1][1] = point
        else:
            result.append([point, point])
    return result


def entry(path, points):
    data = path.read_bytes()
    return {"filename": path.name, "sha256": hashlib.sha256(data).hexdigest(),
            "byteLength": len(data), "ranges": ranges(points)}


with TTFont(latin_path, recalcTimestamp=False) as latin:
    latin_points = set(latin.getBestCmap())
with TTFont(source, recalcTimestamp=False) as original:
    points = set(original.getBestCmap()) - latin_points

chunks = []
for block in sorted({point // chunk_size for point in points}):
    selected = {point for point in points if point // chunk_size == block}
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.hinting = False
    options.layout_features = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=selected)
    subsetter.subset(font)
    name = f"PiCjkSans-U{block * chunk_size:06X}"
    for record in font["name"].names:
        if record.nameID in (1, 3, 4, 6, 16):
            record.string = name.encode(record.getEncoding())
    path = destination / f"{name}.ttf"
    font.save(path)
    actual = set(font.getBestCmap())
    assert actual == selected, "Partition must retain every selected code point"
    chunks.append({"block": block, **entry(path, actual)})
    font.close()

for stale in destination.glob("PiCjkSans-U*.ttf"):
    if stale.name not in {chunk["filename"] for chunk in chunks}:
        stale.unlink()

manifest = {"version": 1, "chunkSize": chunk_size,
            "sourceSha256": hashlib.sha256(source.read_bytes()).hexdigest(),
            "latin": entry(latin_path, latin_points), "chunks": chunks}
output = "// Generated by partition_cjk_font.py with fonttools==4.65.0.\n"
output += "export interface PiFontAsset { filename: string; sha256: string; byteLength: number; ranges: number[][]; }\n"
output += "export const PI_FONT_MANIFEST: { version: number; chunkSize: number; sourceSha256: string; latin: PiFontAsset; chunks: Array<PiFontAsset & { block: number }> } = "
output += json.dumps(manifest, ensure_ascii=True, separators=(",", ":")) + ";\n"
(destination.parent / "font-manifest.ts").write_text(output)
print(f"Built {len(chunks)} chunks; largest {max(chunk['byteLength'] for chunk in chunks)} bytes")
